layout: Do not create object in global scope
endlessm/eos-desktop-extension pull request #73
Opened 2022-10-19 19:43 UTC by jprvita

Objects should only be created in the enable phase of the extension life cycle.

https://phabricator.endlessm.com/T33660

2022-10-19 19:44 UTC, jprvita commented
I believe this addresses review comment 3:
> 3. You cannot create objects in global scope.
>     Global scope is the same as init function (line 220 ui/layout.js).

2022-10-19 19:51 UTC, GeorgesStavracas requested changes
Let me honour your almost perfect effort with a haikai

2022-10-19 19:51 UTC, GeorgesStavracas commented on ui/layout.js
> +var cloneController;
Let me honour your almost perfect effort with a haikai:

> `var` is global scope
> which is not good
> better use `let` here

2022-10-19 20:34 UTC, merged

2022-10-20 16:52 UTC, jprvita commented
> Moving that line to enable isn't enough. You should also null it out in disable. Because we need that variable get garbage collected after disable.

Thanks, addressed in https://github.com/endlessm/eos-desktop-extension/pull/74.